### ISSUE TITLE
unlock-device command should specify need for absolute path

### ISSUE THREAD

**Issue by nkrabben** [awsdocs/aws-snowball-developer-guide#16]
I think this is really a bug with the snowballEdge client, but I'm not sure where to submit a bug report for it.

When using the `unlock-device` tool, the `--manifest-file` argument requires an absolute path to the manifest file location.
Adding a starting slash to the example path might hint at this better.
https://github.com/awsdocs/aws-snowball-developer-guide/blob/fef4cfec8bd7716396a50b03a98df7badd4481a2/doc_source/unlockdevice.md?plain=1#L24

Preferred would be for explicit documentation of this behavior.

There are examples that the `--manifest-file` argument requires an absolute path, e.g. 
https://github.com/awsdocs/aws-snowball-developer-guide/blob/fef4cfec8bd7716396a50b03a98df7badd4481a2/doc_source/unlockdevice.md?plain=1#L31
Although these are not explicit and use non-canonical root folders like `/Downloads`

**Comment by davidmgre** [comment]
Hi @nkrabben, Thank you for providing this feedback.
